### ISSUE TITLE
make compatible with ply based viewers

### ISSUE THREAD

**Issue by chris-aeviator** [WangFeng18/3d-gaussian-splatting#12]
This is an amazing & independent implementation. However I cannot get the pth file working with any ply based viewer. Even when mapping

- pos
- rgb + opa -> rgba
- quat 
- scale

to their corresponding ply parts, renderers like antimatter15/splat won't show anything.

Is it possible to export directly to a compatible format?

**Comment by chris-aeviator** [comment]
ok- so the issue is scale. Where most players render scale as np.exp(scale), an easy fix is to just change their implementation to render scale without the exp. operation

**Comment by eloquentarduino** [comment]
Can you tell me how did you solved? I'm total newbie to this, I've found many viewers for .ply files so I don't know how to handle the .pth file generated by this repo.
