### ISSUE TITLE
Wonky Gimbal Lock in the viewer

### ISSUE THREAD

**Issue by samhodge** [WangFeng18/3d-gaussian-splatting#14]
https://github.com/WangFeng18/3d-gaussian-splatting/assets/86946/c5dd2654-2666-4492-8326-16a1f5f35bc7

I made a COLMAP using Nerfstudio and then trained in your framework, everything was great, until I wanted to look at the result in the viewer

the three rotation axes became confused in gimbal lock.

what is the approach to make the viewer work normally with Nerfstudio prepared data.

I think I tried again just using COLMAP GUI and got the same result.

Is you viewer OpenGL handed or OpenCV handed?

**Comment by brentyi** [comment]
Have you tried the "Reset View" button in the viewer side panel, [implemented here](https://github.com/WangFeng18/3d-gaussian-splatting/blob/2bd1dcc8c9756fd8c6437747446eeef982026a4d/visergui.py#L94-L100)? This should do the same thing as the "Reset Up Direction" button in Nerfstudio.

Possibly the dataset is just written in an difficult-to-navigate orientation by `ns-process-data`/COLMAP. When training in Nerfstudio there are some heuristics for re-orienting the dataset when it's loaded ([this config value](https://github.com/nerfstudio-project/nerfstudio/blob/8a44e46179c465bcaaf28066cbb55777073e3224/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L56)).

**Comment by brentyi** [comment]
For a little more detail on what seems to be happening in your video: the camera controls library being used here and in the Nerfstudio viewer is `camera-controls`, which you can play with in isolation [here](https://yomotsu.github.io/camera-controls/examples/basic.html). It follows the convention of orbits happening around a global "up direction".

By default this is the world Z axis visualized in blue in your video. Hitting the "Reset View" button lets you re-assign this to a new direction, which is computed based on your current camera view.

**Comment by samhodge** [comment]
I will give the reset view button a try in the next few days

**Comment by samhodge** [comment]
https://github.com/WangFeng18/3d-gaussian-splatting/assets/86946/74aa5f8a-eeaf-479a-a6c4-e5b64a87f4fb

Thanks a million.
