### ISSUE TITLE
CUDA out of memory with training iterations

### ISSUE THREAD

**Issue by yqdch** [WangFeng18/3d-gaussian-splatting#5]
Thanks for your great work!
With the latest version of the code，I notice the GPU memory increasing with training iterations and eventually overflowing. I'm wondering how to fix it, thanks.

**Comment by WangFeng18** [comment]
You can reduce improve the grad_thresh, e.g., setting the grad_thresh to larger as 0.05, this will generate less gaussians with similar metrics. I have tested on 3090Ti and in the original paper, they also claim a whole implementation will occupy about 20GB GPU memory.

**Comment by yqdch** [comment]
> 

Hi, I test on A6000 with 48GB memory. The problem is memory usage progressively increasing and eventually overflowing. Perhaps some variable memory has not been properly released?

**Comment by WangFeng18** [comment]
Try this one.
python train.py --exp garden --grad_thresh 0.000002 --debug 1 --ssim_weight 0.1 --lr 0.002 --use_sh_coeff 0 --grad_accum_method mean --grad_accum_iters 300 --split_thresh 0.08

**Comment by yqdch** [comment]
> Try this one. python train.py --exp garden --grad_thresh 0.000002 --debug 1 --ssim_weight 0.1 --lr 0.002 --use_sh_coeff 0 --grad_accum_method mean --grad_accum_iters 300 --split_thresh 0.08

Thank you so much for the reply. 
Finally I found there are some bugs in ssim computing, upgrading the torchmetrics library to the latest version works.
