### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by hardikdava** [WangFeng18/3d-gaussian-splatting#6]
Thank you for this amazing work. I was testing it and trying to run it first time and I am getting following errors. Can you help me with this?

```
  File "/3d-gaussian-splatting/train.py", line 374, in <module>
    gaussian_splatter = Splatter(
  File "/3d-gaussian-splatting/splatter.py", line 427, in __init__
    self.set_camera(0)
  File "/3d-gaussian-splatting/splatter.py", line 490, in set_camera
    self.current_w2c_quat = self.w2c_quats[idx]
IndexError: list index out of range
```

My command to start training is:

```
python train.py --data data/sample_data/ --exp exp_1
```

My sample data is processed with colmap as structured as following:

```
-sample_data
    -images/
    -sparse/0/*.bin
    -transforms_train.json
```

**Comment by NPU-YanChi** [comment]
I meet the same problem, have you already solved this?

**Comment by NPU-YanChi** [comment]
I have solve this issue by 
cp -r images/ images_4/
in colmap output dataset
